import Navbar from "../components/navbar";
import "./globals.css";

export const metadata = {
  title: "PDF Translator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
